### ISSUE TITLE
Switch debugger array to dictionary

### ISSUE THREAD

**Issue by djpowers** [mcasper/vim-infer-debugger#18]
I was wondering what you thought about switching the `debugger_array` to instead use a [dictionary](http://learnvimscriptthehardway.stevelosh.com/chapters/37.html).

My main reason for this suggestion is so that specifying your own debuggers would only require a single line of code for each one, without the need to copy the entire existing array to avoid overwriting anything.

I'm not super familiar with Vimscript, so my apologies if this isn't technically doable. If it is possible, I'd be happy to take a shot at implementing it. Either way, I appreciate your work on the plugin; it's super helpful!

**Comment by mcasper** [comment]
I think that's a fantastic idea! I have no idea why I didn't originally implement it using a dictionary, most likely because I had no idea they were a data type in vimscript ¯\_(ツ)_/¯ 

I would happily accept a PR converting the plugin to use a dictionary, fire away!
